export const SEARCH_DATA_REQUEST = "SEARCH_DATA_REQUEST";
export const SEARCH_DATA_SUCCESS = "SEARCH_DATA_SUCCESS";
export const SEARCH_DATA_FAILER = "SEARCH_DATA_FAILER";

export const SEARCH_ADDON_REQUEST = "SEARCH_ADDON_REQUEST";
export const SEARCH_ADDON_SUCCESS = "SEARCH_ADDON_SUCCESS";
export const SEARCH_ADDON_FAILER = "SEARCH_ADDON_FAILER";

export const SET_SEARCH = "SET_SEARCH";

export const ADD_ALL_SEARCH = "ADD_ALL_SEARCH";
